;
; File generated by cc65 v 2.19 - Git 6ac4aa4e2
;
	.fopt		compiler,"cc65 v 2.19 - Git 6ac4aa4e2"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_printf
	.export		_main

.segment	"RODATA"

S0001:
	.byte	$48,$65,$6C,$6C,$6F,$20,$57,$6F,$72,$6C,$64,$0A,$00

.DEFINE string1 "hey"

S0002:
	.byte	string1,$0A,$00




; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

    ; print Hello World
	lda     #<(S0001)
    ldx     #>(S0001)
	jsr     pushax
	ldy     #$02
	jsr     _printf
    ldx     #$00
	lda     #$00

    ; print hey
    lda     #<(S0002)
    ldx     #>(S0002)
	jsr     pushax
	ldy     #$02
	jsr     _printf
    ldx     #$00
	lda     #$00

    .segment	"RODATA"
    ldx     #4
    stx     $0300
    io =   $0300
    TEST: .byte .sprintf("%d",io),$0A,$00

    .segment    "CODE"
    lda     #<(TEST)
    ldx     #>(TEST)
	jsr     pushax
	ldy     #$02
	jsr     _printf
    ldx     #$00
	lda     #$00
    
    


	jmp     L0001
L0001:	rts

.endproc

